### ISSUE TITLE
🐛 [Bug] Core/MMaps update mmap error

### ISSUE THREAD

**Issue by w5860363** [vmangos/core#2439]
https://github.com/vmangos/core/commit/1430303bbe276416fdc0213b0271d0f981704fb7
Testing uses high-definition extraction to detect MMAP faults in areas below sea level

For example, Stormwind Prison, the birthplace of Night Elves

NPC will stop moving
![QQ图片20240119020315](https://github.com/vmangos/core/assets/1938163/07c757d5-ebad-4b2f-a262-bdf905d09774)

Map: 1 (Kalimdor) Zone: 141 (Tadahir) Area: 188 (Shadow Valley)

X: 10327.372070 Y: 852.100525 Z: 1327.963989 Orientation: 2.828253

Grid [30,12] cell [9,5] InstanceID: 0

ZoneX: 58.182968 ZoneY: 44.313160

GroundZ: 1327.963989 FloorZ: 1327.963989 Have height data (Map: 1 VMap: 1)

and
![2](https://github.com/vmangos/core/assets/1938163/a27dc388-eade-4514-b449-0b85e1d23396)

Map: 0 (Eastern Kingdoms) Zone: 36 (Alterac Mountains) Area: 281 (Alterac Ruins)

X: 564.644287 Y: -320.823517 Z: 150.669800 Orientation: 2.745785

Grid [32,30] cell [6,0] InstanceID: 0

ZoneX: 39.434174 ZoneY: 50.108345

GroundZ: 150.667816 FloorZ: 150.667816 Have height data (Map: 1 VMap: 1)

**Comment by ratkosrb** [comment]
You should give coordinates of the place you are talking about. Type .gps command and take a screenshot.

**Comment by Wall-core** [comment]
> [1430303](https://github.com/vmangos/core/commit/1430303bbe276416fdc0213b0271d0f981704fb7) Testing uses high-definition extraction to detect MMAP faults in areas below sea level
> 
> For example, Stormwind Prison, the birthplace of Night Elves
> 
> NPC will stop moving

Fixed here: #2436

**Comment by w5860363** [comment]
@Wall-core This is today's test
I found that the extracted files are much smaller in size than the regular version

**Comment by Wall-core** [comment]
![image](https://github.com/vmangos/core/assets/90075138/fb8930be-23d5-4fd6-8c23-354f94beb3e9)
working fine for me, that commit fixed the issue which existed previously. Ensure you are rebuilding and using the latest extractors; run all four from command prompt with the following commands:
```
mapextractor.exe
vmapextractor.exe
vmap_assembler.exe
movemapgen.exe 34
```
This will generate new maps, vmaps, and movemaps for Stormwind Stockades. Test the new build for Stockades.

**Comment by w5860363** [comment]
@Wall-core 
![1](https://github.com/vmangos/core/assets/1938163/5015ebce-2100-4484-91f1-b2f40bd502e0)
Re extraction did not solve the problem

**Comment by zxnhrdz** [comment]
After testing, the above problem does exist. The #2439 may have solved part of the problem, but created a new bug.

**Comment by zxnhrdz** [comment]
![image](https://github.com/vmangos/core/assets/110412571/be2681e6-4904-4f78-bb78-e1a2b7f89127)
Problems are now occurring where there were none before, and this is just one example.

**Comment by Wall-core** [comment]
were you using the repack mmaps previously? or a full extraction from scratch?

**Comment by w5860363** [comment]
@Wall-core @Under only high-definition extraction, conventional extraction is not a problem

**Comment by ratkosrb** [comment]
The files in the repack were already high definition.

**Comment by Wall-core** [comment]
@w5860363 I'm looking in to the issue closely. Previously, this issue was present on my project and my recent commit fixed it for us.

**Comment by zxnhrdz** [comment]
The problem is that it arises after a full re-extraction. There were no such problems before. To verify the problem, I was reextracting the latest mmaps and the bug was created.

**Comment by ratkosrb** [comment]
The issues seem to be caused by https://github.com/vmangos/core/commit/2447de4e5b69347bb724b14d4c268720e925ce78
Do a git pull and try extracting mmaps again.

**Comment by w5860363** [comment]
https://github.com/vmangos/core/assets/1938163/4a0eca4d-667a-4dac-a11f-17b2200cad6c

@ratkosrb pull work
